#:schema node_modules/wrangler/config-schema.json
name = "subnew"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "0d227de1eda54020aacf3505ce0b260c" }
]
